### PR TITLE
add initial workflow

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by winrid** [comment]
@andy5995 Thanks! What we really need to do next is probably have auto formatting setup (not just linting).

**Comment by andy5995** [comment]
@winrid Can you enable Actions on this repo? I wanna try fixing the clang build...

**Comment by winrid** [comment]
@andy5995 Sure. any reason for preference for clang? I think others and I have been using gcc on Linux and mingw/gcc on Windows.

**Comment by andy5995** [comment]
I personally don't have a preference, but ensuring a clang build will make it easier for any distro packagers or other folks who prefer clang.

**Comment by winrid** [comment]
I have enabled Actions - let me know if there's anything else I need to do.

**Comment by andy5995** [comment]
> @andy5995 Thanks! What we really need to do next is probably have auto formatting setup (not just linting).

Widelands has something like that https://github.com/widelands/widelands/blob/6f47c54d395561a0264724b5959fd98a2dd56430/.github/workflows/format.yaml

**Comment by winrid** [comment]
Nice! Adopting that would be a huge improvement.

**Pull request merged**
