### PR TITLE
Fix more shadow warnings

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Review by winrid — APPROVED** [review]
I guess this is fine. I personally don't see any issue with constructors like this:

```
this->x = x
```

I do this every day, and I don't think you can expect me to stop. :P So some of these will come back as I write more code. I think the shadow warning is valuable in the larger non-constructor methods. I am not sure if it's able to be disabled in constructors.

**Comment by andy5995** [comment]
Ok, I won't expect you to stop, but then we should remove -Wshadow from the build flags. I don't see there's any way to disable it in certain cases.

It seems that if "this->" is accidentally omitted from, "this->map_loc_x", and "map_loc_x" is locally declared as a function parameter or local variable, the compiler will never give any error or warning, as far as I can tell.

And if you're using a variable that hasn't been declared locally or as a func parameter, it's clearly a member of the class, so confusion can't really happen (though it might take a few moments to verify the variable hasn't already been locally declared).

That's not say I'm opposed to still using "this->..." even if it's not necessary, but because "this->" isn't needed, I'd recommend having different names for loc vars.

Having said all that, I'll go along with what you decide. Here's a few more POVs:

>Can compiler warnings be disabled when using shadow variables that are already declared as public members of a class?

Phind says...
https://www.phind.com/search?cache=f0l8sajnqiercze6qw04gucm

ChatGPT says...

```
In general, it's not advisable to disable compiler warnings, as they serve as important indicators of potential issues or code quality problems. However, there may be cases where you have a good reason to do so. When dealing with shadowing variables that are already declared as public members of a class, it's important to understand the implications and consider alternative approaches to avoid the need for disabling warnings.

Shadowing occurs when a variable in a nested scope has the same name as a variable in an outer scope. In the context of classes, this often happens when a local variable or a parameter has the same name as a member variable. While it is technically allowed, it can lead to confusion and unintended behavior.

If you find yourself in a situation where shadowing is necessary, consider the following alternatives before disabling warnings:

1. **Rename the local variable or parameter:** Give the local variable or parameter a different name to avoid shadowing the class member variable. This makes the code more readable and eliminates the need to disable warnings.

   ```cpp
   class MyClass {
   public:
       int myVariable;

       void myMethod(int localVar) {
           // Rename localVar to avoid shadowing
           int modifiedVar = myVariable + localVar;
           // ...
       }
   };
   ```

2. **Use `this` pointer:** If the shadowed variable is a member variable, you can use the `this` pointer to explicitly refer to the member variable and avoid ambiguity.

   ```cpp
   class MyClass {
   public:
       int myVariable;

       void myMethod(int myVariable) {
           // Use this->myVariable to refer to the member variable
           int modifiedVar = this->myVariable + myVariable;
           // ...
       }
   };
   ```

3. **Reconsider the design:** If shadowing is causing confusion, it might be a sign that the code could benefit from a redesign. Consider refactoring your code to make it clearer and avoid the need for shadowing.

If after careful consideration you still find it necessary to disable compiler warnings, you can use compiler-specific directives or pragmas to suppress specific warnings. However, it's crucial to document the reasons for doing so and ensure that the code remains maintainable and understandable. Keep in mind that disabling warnings should be a last resort and used sparingly.
```

**Comment by winrid** [comment]
It looks like we can disable this for constructors with clang:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78147

Let's do that

**Comment by andy5995** [comment]
I don't understand. There would still be too many shadow warnings to deal with when using gcc.

**Comment by winrid** [comment]
Yeah was still looking into GCC. Was hoping there was a solution. If not I'll turn it off, it doesn't add any value compared to the real issues we have.

**Comment by andy5995** [comment]
Ok, sounds good.

**Pull request closed without merging**
