### PR TITLE
Make game_config cli option work as expected

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by winrid** [comment]
So does this mean it takes an absolute path now? Will existing server setups break?

**Comment by andy5995** [comment]
It can take an absolute or relatative path. If it's in ~/.netpanzer, it would have to be specified as ~/.netpanzer or the relative path to the ~/.netpanzer directory.

**Comment by winrid** [comment]
If the latter works then it's good (otherwise would probably have to add it as a separate option)!

For example I think all current servers use "config/blah.cfg" where the config dir is in `.netpanzer`

If you verified that then good to merge

**Comment by winrid** [comment]
@ph2708 you will have to update your server config paths with this change.

**Review by winrid — APPROVED** [review]

**Pull request merged**
