### PR TITLE
Update Credits

### PR DESCRIPTION
**Pull request by winrid**
- Remove incorrect info about website (until website is improved).
- Moved authors that worked on game 20yrs ago to bottom, moved release list to top.
- Updated current dev team list.

@Jammyjamjamman Finally prepping 0.9.x release. I didn't know if you wanted your full name in credits, LMK.

### CODE REVIEW

**Comment by winrid** [comment]
Screenshot_2024-07-21_12-00-35

**Comment by winrid** [comment]
fixed release order to newest first...

Screenshot_2024-07-21_12-07-42

**Comment by winrid** [comment]
Ok, this has been open for a week, merging!

**Comment by Jammyjamjamman** [comment]
Very late responding sorry but just fyi the way you've written it with my username handle only is fine, thanks.

**Pull request merged**
