### PR TITLE
SDL2

### PR DESCRIPTION
**Pull request by winrid**
Compiles. Still working on:

- [x] Getting things rendering again :) Crashes on setting the palette - working on it.
- [x] Getting things rendering - segault somewhere else now.
- [x] Getting things rendering - window now blank - pass blt surface data to new Renderer to take advantage of new fullscreen scaling in sdl2?
- [x] Events are not being captured? Why?
- [x] Fix "Couldn't open audio device"
- [x] Fix segfault on joining map.
- [x] Proper keyboard (and maybe unicode in chat?) support.
- [x] Testing on Linux
- [ ] Testing on Windows
- [ ] Testing on Mac

### CODE REVIEW

**Comment by winrid** [comment]
@futes So it turns out instead of uncommenting we can change "sdl-config" to "sdl2-config" and that solves the problem. I'm not actually sure where this gets defined... will make another pass on SConstruct before merge.

**Comment by futes** [comment]
> @futes So it turns out instead of uncommenting we can change "sdl-config" to "sdl2-config" and that solves the problem. I'm not actually sure where this gets defined... will make another pass on SConstruct before merge.
> 
> Now it segfaults when joining a game, will investigate.

I guess your solution with sdl-config is preferable.

Program crashes also when pressing special keys and I discovered why.
SDLEvents sends event.key.keysym.sym to KeyboardInterface which uses those values as index of an array (used to check keys status). Apparently these values in old SDL were all max SDL_NUM_SCANCODES (that is 512). But now in SDL2 the values of special keys are like huge ints which of course break the index.
Please also note that to catch a key status there is now a function provided by the lib: SDL_GetKeyboardState().
And remember that we will need both event.key.keysym.sym and event.key.keysym.scancode in the newly redesigned keyboard interface -> to manage text input and commands.

I wanted to write  a patch for this but it's not easy without having access to game to test chat etc. So we should probably focus on the video issue now.

**Comment by winrid** [comment]
Yep I'm aware of the keyboard stuff and how sdl2 works now :) I will be rewriting the keyboard after video is done, or adding the old patch back in if not feasible.

**Comment by winrid** [comment]
@futes I've made a quick pass on the keyboard interface so it doesn't immediately crash now, and fixed some issues with the screen resolution selection. Still working on overall stability.

**Comment by winrid** [comment]
@futes The video instability issues are fixed now as far as I can tell. I am still looking to optimize it further (game is using about 30% of one cpu core while in game on my 2018 laptop).

**Comment by winrid** [comment]
I tested switching the renderer to SDL_BlitSurface && SDL_UpdateWindowSurface and there was only about 5-10% performance improvement, so I think I'm going to stick with the renderer and recreating one texture every frame. This solution is actually really nice because it removes a lot of code, and the resolution scaling is more reliable.

**Comment by futes** [comment]
> I tested switching the renderer to SDL_BlitSurface && SDL_UpdateWindowSurface and there was only about 5-10% performance improvement, so I think I'm going to stick with the renderer and recreating one texture every frame. This solution is actually really nice because it removes a lot of code, and the resolution scaling is more reliable.


Excellent work winrid!

Still some minor things to fix up, but hey we're nearly there.

I agree that keeping SDL_Renderer will grant us many new features and possibilities, provided the cost is acceptable.

As to the CPU spikes caused by video rendering, a later implementation of 'threads' could produce a nicely balanced and shared load between physical and virtual CPUs.

**Comment by winrid** [comment]
Thanks! I hope to figure out the keyboard issues soon. Let me know if the performance is okay for you, it is playable (just don't try to backspace in chat, lol)

**Comment by winrid** [comment]
@futes Keyboard now works and is stable. Some functionality, like special characters, aren't supported yet.
I'm looking into supporting SDL2's SDL_TextInputEvent.

**Comment by winrid** [comment]
@futes nevermind, it now uses the new SDL2 text input system. Please test :)

**Comment by futes** [comment]
Tested and the input is Ok now. I think while the new chat should be Unicode (and SDL2 helps in this), the desktop tabs input boxes and the dedicated server console input should stay ASCII or even a printable subset of it. Same thing for the usernames (player names) and Outpost names as well as the filenames. We should switch to Unicode in the chat only imho.

And in case we need a new 'universal' bitmap font (must be bitmap in 8bit indexed color palette) I have found this: https://unifoundry.com/unifont/index.html (they even provide a hex format which could help).

I spent couple of hours today trying to understand why once in a map (game mode) I cannot select units and (so) I cannot move or shoot... I guess you're experiencing this too right? This seems to be the last effect of SDL2 update yet to be fixed.

**Comment by winrid** [comment]
@futes Mouse issues fixed now, seems playable.

**Comment by winrid** [comment]
@futes will test compilation on OSX tomorrow.

I assume you already tested Windows since you say it works.

If Mac looks good I'd like to merge to dev, and then open another PR for updating fonts (I also want to see about adding a slightly larger font for the UI fields).

**Comment by futes** [comment]
> @futes will test compilation on OSX tomorrow.
> 
> I assume you already tested Windows since you say it works.
> 
> If Mac looks good I'd like to merge to dev, and then open another PR for updating fonts (I also want to see about adding a slightly larger font for the UI fields).

I normally test it in Linux and it's OK. In Windows there might be some problems, maybe not even related to latest changes... it's a long story. In the last days I tried to update compiling toolchain in Windows 10. I had many problems with Python & scons versions compatibility. At a moment all the compiling errors due to 'throw' that you fixed in Linux were still there in Win. Finally after playing a bit with versions of Python and scons it looked like the latter was completely broken! I am confused.

Anyway I am working on a PR too, related to the new auth system and the network replacement in np. 

If you're able to test it in OSX I am happy. I've always dreamed about having such version.

**Comment by winrid** [comment]
@futes interesting, will investigate win10 compiling then, and maybe add instructions to the readme.

**Comment by futes** [comment]
> @futes interesting, will investigate win10 compiling then, and maybe add instructions to the readme.

A general consideration: while I agree that constantly checking the source on all platform is a good practice, let's not waste too much time now on fixing some very old code (the network part was probably written in the 90s) which we could soon replace with some well maintained library.

P.S. The best compiling result in Windows I had it with MSYS2 and the mingw32 environment (https://www.msys2.org/docs/environments/). I could compile the SDL2 dev and the SDL2_mixer, install python, scons (comes in an older version) and GCC toolchain. Then netpanzer compiling was stopped by many issues...

**Comment by futes** [comment]
And whatever strategy you adopt to create  a toolchain in Win, don't make these 2 stupid mistakes I did!
1) Be sure you don't have some forgotten version of Visual Code installed or mingw will choose it instead of GCC!
2) If you install a fresh Python in Win be sure  to tick the checkbox: "let python add PATH for you"! :D

**Comment by winrid** [comment]
@futes Almost got compiling on win10 with MinGW (not vs code). had to fix sconstruct file a little, fix is in this sdl2 branch. Also had to remove "using namespace std", interestingly, otherwise we run into a fun `byte is ambiguous` error.

Had to also download latest mingw for latest gcc (although you really only need a version of gcc released after ~2017): https://winlibs.com/

you will also need the mingw distribution of sdl and sdl mixer:
- https://lazyfoo.net/tutorials/SDL/01_hello_SDL/windows/mingw/index.php
- https://github.com/libsdl-org/SDL_mixer/releases/tag/release-2.6.3

Currently getting this, will look more next week:

```
b'C:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lnplua: No such file or directory\r\nC:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lnpnetwork: No such file or directory\r\nC:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lnpphysfs: No such file or directory\r\nC:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lSDLMain: No such file or directory\r\ncollect2.exe: error: ld returned 1 exit status\n'
```

Anyway, none of this is really related to the SDL2 migration. Do you want to merge it? :) I will do the rest of the unicode stuff in another PR.

**Comment by winrid** [comment]
Merged, since compile issues on windows are not related to this branch and no regressions have been found.

Creating separate PRs for windows and unicode.

**Comment by futes** [comment]
OK. I would like to make a big PR concerning the new authentication system and possibly - as a further test - a general network code replacement. How can I do it in Github just like you did with SDL2? I mean a 'suspended' PR opened to comments and reviews. Could you show me the single steps in Github? Thx. Should I first create another branch?

**Comment by winrid** [comment]
Hey @futes 
Sure!

1. Create a branch - probably off `dev`
2. You can go to the repo: https://github.com/netpanzer/netpanzer
3. In top left, you'll see dropdown for "master" - change that to your new branch (you'll have to push it to origin).
4. At top of page there should now be a "create pull request" button.
5. It will ask you which branch is the "base", which means the target branch. So you'll want it to look like `dev <- mybranchname`.

Then it will just be in an open state, and you can continue to commit to your branch as normal.

**Pull request merged**
