### PR TITLE
Improving Right Mouse Movement + Removing Black Bars

### LINKED ISSUE #159: Holding down the right mouse buttong to scroll through map doesn't work as expected
Reported by @ph2708 

>A question from two players was that when holding down the right mouse button to move around the map, it is very different from how it was before, as it loses the precision of moving around the map.

### PR DESCRIPTION
**Pull request by winrid**
Fixes #159 

Status: More linear now. Weird issue with cursor being jittery.

### CODE REVIEW

**Comment by winrid** [comment]
@andy5995 can you see if the right mouse movement is better for you now in this branch, but it doesn't zoom to the top corner anymore? :)

**Comment by andy5995** [comment]
> @andy5995 can you see if the right mouse movement is better for you now in this branch, but it doesn't zoom to the top corner anymore? :)

With this branch, now it zooms to the top-left corner, whereas before it didn't.

**Comment by winrid** [comment]
Well, thanks for testing. So, it works on Windows, but not Linux! Will investigate further. At the very least can add an ifndef until I figure that out.

**Comment by winrid** [comment]
Reproducible on Windows too, if full screen.

**Pull request merged**
