### PR TITLE
refactor Credits (closes #99)

### LINKED ISSUE #99: Remove a few lines from the credits screen and fix URL
Ok if I do some work on the Credits screen?

https://github.com/netpanzer/netpanzer/blob/eadcbc5b1fad0084c26a1c77eace8828283b9bab/src/NetPanzer/Views/MainMenu/CreditsScrollView.cpp#L40-L60

The URL is still SourceForge.

I'd like to remove the description and version because it seems like it's not necessary (goal is to reduce code maintenance). I feel that if someone is looking at the credits screen, they've already read the game description somewhere else.

As for the URL, should I make a Package::GetUrl function?

### PR DESCRIPTION
**Pull request by andy5995**
@winrid This segfaults when I hit the 'Credits' tab. Any idea why? I'm passing a const char* like the insert function wants...

### CODE REVIEW

**Comment by andy5995** [comment]
I still got format the string and change a few things, but my debug output to stderr looks right:

```
  This application is free software under the terms of the
    Gnu General Public license (GPL). See the COPYING file for details.

  Source and binaries at: http://github.com/netpanzer/netpanzer/releases/

  Please visit www.NETPANZER.info
  - for binaries, maps, flags, related tools and news
  - and don't forget to register your nickname for the ranking

  Current Development Team
  - Devon Winrick (winrid)
  - Fulvio Testi (fu)


  Authors

  Additional graphics:
  Peter Lisker (Nessie), Jesus Eugenio (Silvestre)


  Original Game (Pyrosoft):
  Vlad Rahkoy, Skip Rhudy, Matt Bogue, Clint Bogue

  Linux Port, Polishing, Packaging and Related Tools:

      Matthias Braun, Ivo Danihelka, Hollis Blanchard, Hankin Chick, 
    BenUrban
  Tyler Nielsen, Bastosz Fenski, Tobias Blerch, Ingo Ruhnke

  0.8.3 Release:
  Aaron Perez (krom), C-D, fu

  0.8.4 Release up to 0.8.5-test-1:
  Aaron Perez (krom), Laurant Jacques (Wile64), C-D, fu

  0.8.7 Release:
  Fulvio Testi (fu), Guido Ueffing (Lohengrin)
```

**Comment by winrid** [comment]
Didn't look yet but insert() might only take a single line of text? font rendering might be trying to write out bounds on a surface that has an explicit height set, although i'd expect you'd get an assertion error in that case. valgrind should say why.

**Comment by winrid** [comment]
Yeah, that's probably why. Instead of using insert() you might want to create a surface and blit the text to it yourself.
I would honestly just go back to using one insert() per line, and this will get refactored when I rewrite the UI system to get rid of our custom text/layout stuff.

**Comment by andy5995** [comment]
insert takes a const char* and it seems to do newlines automatically. So in this case, I've tried replacing all the calls to insert with a single call, using one big string with newlines.

I'm not too handy with valgrind, but I did get some info with gdb

```
gdb) info stack
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:88
#1  0x00005555555b7904 in Surface::bltString (this=0x555556cd9db0, x=1, y=26, 
    str=0x0, color=@0x7fffffffda7f: 1 '\001') at ../src/Lib/2D/Surface.cpp:1390
#2  0x00005555555f3cbf in CreditsScrollView::drawHelpText (
    this=0x555556a4ed10, dest=...)
    at ../src/NetPanzer/Views/MainMenu/CreditsScrollView.cpp:153
#3  0x00005555555f3bac in CreditsScrollView::doDraw (this=0x555556a4ed10, 
    viewArea=..., clientArea=...)
    at ../src/NetPanzer/Views/MainMenu/CreditsScrollView.cpp:124
#4  0x0000555555607e49 in View::draw (this=0x555556a4ed10, surface=...)
    at ../src/NetPanzer/Views/Components/View.cpp:366
#5  0x0000555555600b2c in Desktop::draw (surface=...)
    at ../src/NetPanzer/Views/Components/Desktop.cpp:307
#6  0x00005555555974da in PlayerGameManager::graphicsLoop (this=0x5555558af270)
    at ../src/NetPanzer/Interfaces/PlayerGameManager.cpp:228
#7  0x000055555559cd6d in BaseGameManager::mainLoop (this=0x5555558af270)
    at ../src/NetPanzer/Interfaces/BaseGameManager.cpp:173
#8  0x0000555555598f30 in PlayerGameManager::mainLoop (this=0x5555558af270)
    at ../src/NetPanzer/Interfaces/PlayerGameManager.cpp:486
#9  0x0000555555575ac9 in netpanzer_main (argc=1, argv=0x7fffffffdf18)
    at ../src/NetPanzer/Core/main.cpp:377
#10 0x0000555555575cce in main (argc=1, argv=0x7fffffffdf18)
    at ../src/NetPanzer/Core/main.cpp:411
```

We don't need to spend time debugging this; I'll go back to the old way and forget about my big string ways.

**Comment by andy5995** [comment]
>I would honestly just go back to using one insert() per line

Ok. I got your last message right after I posted mine.

**Comment by winrid** [comment]
It's definitely good to know of this issue, though. Will fix sooner if new UI stuff takes too long.

**Review by winrid — APPROVED** [review]
wasn't sure if you were waiting on my approval, but LGTM

**Pull request merged**
